"""create initial schema

Revision ID: 45ac6c3034aa
Revises: 
Create Date: 2026-07-21 15:12:58.873907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ac6c3034aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('display_code', sa.String(length=8), nullable=False),
    sa.Column('public_code', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_code'),
    sa.UniqueConstraint('public_code'),
    sa.UniqueConstraint('username')
    )
    op.create_table('queues',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('queue_number', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('queue_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'CALLING', 'DONE', name='queuestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'device_id', 'queue_date', name='uq_queue_device_per_day')
    )
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.create_index('ix_queue_shop_date', ['shop_id', 'queue_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.drop_index('ix_queue_shop_date')

    op.drop_table('queues')
    op.drop_table('shops')
    # ### end Alembic commands ###
